name: Tag Version
on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Needed to get all tags
          fetch-depth: 0
      # Prevents more than once action from running at once, ensuring tags are atomic.
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  Done by changelog?
#      - name: Tag
#        uses: ./.github/actions/tag-version
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
